version: "3.9"
services:
  psql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database

    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data

  web:
    build: .
    scale: 6
    ports:
      - "8000:5000"
    depends_on:
      - psql

